### ISSUE TITLE
Error in display - field

### ISSUE THREAD

**Issue by soft4tec** [vadimpopa/Ux.field.Multiselect#8]
Hello,
first, I have to tell you, this is a great component. I love it.

But I found a little Bug in the display-field. The text is wrong, when there are records with ids, that have the same part in the string. Like '111', '11', '1'. This behavior based on that the Ext function "findRecord" find the first occurence. For my Example, when you have the id : '1' it will find '111' first.
To avoid this, you can configure it more strict.

Add in your source : 
convertValue: function(value,fieldIn,fieldOut){
   : 
   **item = store.findRecord(fieldIn,value[i],0,false,true,true);**
   : 
}

Regards from Germany
Marco

**Comment by vadimpopa** [comment]
added that, thanks.
